spring:
  application:
    name: schools
  config:
    import: optional:configserver:http://localhost:8888
  graphql:
    graphiql:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
application:
  config:
    students-url: "http://localhost:8222/api/v1/students"

