spring:
  application:
    name: gateway
  graphql:
    graphiql:
      enabled: true
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
