server:
  port: 8222

spring:
  application:
    name: gateway
  graphql:
    graphiql:
      enabled: true
  cloud:
    gateway:
      routes:
        - id: students
          uri: lb://students
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: lb://schools
          predicates:
            - Path=/graphql/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
