server:
  port: 8090

spring:
  application:
    name: students
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_db?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

application:
  config:
    students-url: "http://localhost:8080/students"


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
