server:
  port: 8060
  servlet:
    context-path: /ws

logging:
  level:
    org.springframework: DEBUG
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: teachers
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_db?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

application:
  config:
    teachers-url: "http://localhost:8222/teachers"


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka