server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-server
  graphql:
    graphiql:
      enabled: true
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
